TESTBENCH_CONFIGS = [
    {
        "name": "diffusion_no_psf",
        "num_iters": 300,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_k_auto": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 15,
        "sigma_gaussian": None,
        "motion_length": None,
        "angle_motion": 0.0,
        "fried_parameter_turbulence": None,
        "distortion_strength_turbulence": None,
        "seed_turbulence": None,
        "psf_types": ["none"],
    },
    {
        "name": "diffusion_gaussian_only",
        "num_iters": 300,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_k_auto": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 15,
        "sigma_gaussian": 2.5,
        "motion_length": 7,
        "angle_motion": 0.0,
        "fried_parameter_turbulence": None,
        "distortion_strength_turbulence": None,
        "seed_turbulence": None,
        "psf_types": ["gaussian"],
    },
    {
        "name": "diffusion_motion_only",
        "num_iters": 300,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_k_auto": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 15,
        "sigma_gaussian": None,
        "motion_length": 9,
        "angle_motion": 20.0,
        "fried_parameter_turbulence": None,
        "distortion_strength_turbulence": None,
        "seed_turbulence": None,
        "psf_types": ["motion"],
    },
    {
        "name": "diffusion_turbulence_only",
        "num_iters": 300,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_k_auto": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 15,
        "sigma_gaussian": None,
        "motion_length": None,
        "angle_motion": 0.0,
        "fried_parameter_turbulence": 1.8,
        "distortion_strength_turbulence": 0.8,
        "seed_turbulence": 23,
        "psf_types": ["turbulence"],
    },
    {
        "name": "diffusion_gaussian_motion",
        "num_iters": 300,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_k_auto": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 17,
        "sigma_gaussian": 2.2,
        "motion_length": 9,
        "angle_motion": 15.0,
        "fried_parameter_turbulence": None,
        "distortion_strength_turbulence": None,
        "seed_turbulence": None,
        "psf_types": ["gaussian", "motion"],
    },
    {
        "name": "diffusion_motion_turbulence",
        "num_iters": 300,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_k_auto": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 17,
        "sigma_gaussian": 0.0,
        "motion_length": 11,
        "angle_motion": 25.0,
        "fried_parameter_turbulence": 1.6,
        "distortion_strength_turbulence": 0.85,
        "seed_turbulence": 29,
        "psf_types": ["motion", "turbulence"],
    },
    {
        "name": "diffusion_rml_only",
        "num_iters": 300,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_k_auto": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 15,
        "sigma_gaussian": None,
        "motion_length": None,
        "angle_motion": 0.0,
        "fried_parameter_turbulence": None,
        "distortion_strength_turbulence": None,
        "seed_turbulence": None,
        "bandwidth_rml": 0.35,
        "seed_rml": 7,
        "psf_types": ["rml"],
    },
]
