TESTBENCH_CONFIGS = [
    {
        "name": "baseline_no_priors",
        "num_iters": 100,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 15,
        "sigma_gaussian": 2.0,
        "angle_motion": 0.0,
    },
    {
        "name": "pink_noise_only",
        "num_iters": 100,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.1,
        "lambda_diffusion": 0.0,
        "kernel_size": 15,
        "sigma_gaussian": 2.0,
        "angle_motion": 45.0,
    },
    {
        "name": "diffusion_only",
        "num_iters": 100,
        "lr_x": 5e-3,
        "lr_k": 5e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.01,
        "kernel_size": 15,
        "sigma_gaussian": 2.0,
        "angle_motion": 0.0,
    },
    {
        "name": "pink_plus_diffusion",
        "num_iters": 200,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.005,
        "kernel_size": 21,
        "sigma_gaussian": 1.8,
        "angle_motion": 30.0,
    },
    {
        "name": "large_kernel_diffusion",
        "num_iters": 150,
        "lr_x": 1e-2,
        "lr_k": 5e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 5e-4,
        "lambda_k_center": 5e-4,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.02,
        "kernel_size": 31,
        "sigma_gaussian": 3.0,
        "angle_motion": 75.0,
    },
    {
        "name": "short_run_fast",
        "num_iters": 50,
        "lr_x": 2e-2,
        "lr_k": 2e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 13,
        "sigma_gaussian": 1.2,
        "angle_motion": 0.0,
    },
    {
        "name": "aggressive_lr_pink",
        "num_iters": 80,
        "lr_x": 2e-2,
        "lr_k": 2e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 5e-4,
        "lambda_k_center": 5e-4,
        "lambda_pink": 0.15,
        "lambda_diffusion": 0.0,
        "kernel_size": 17,
        "sigma_gaussian": 2.5,
        "angle_motion": 25.0,
    },
    {
        "name": "strong_image_prior",
        "num_iters": 120,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.02,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 15,
        "sigma_gaussian": 1.5,
        "angle_motion": 0.0,
    },
    {
        "name": "centered_kernel_focus",
        "num_iters": 120,
        "lr_x": 8e-3,
        "lr_k": 8e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 5e-4,
        "lambda_k_center": 2e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.01,
        "kernel_size": 19,
        "sigma_gaussian": 2.2,
        "angle_motion": 15.0,
    },
    {
        "name": "tiny_kernel_quick",
        "num_iters": 60,
        "lr_x": 1.5e-2,
        "lr_k": 1.5e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.0,
        "kernel_size": 9,
        "sigma_gaussian": 1.0,
        "angle_motion": 0.0,
    },
    {
        "name": "medium_kernel_balanced",
        "num_iters": 150,
        "lr_x": 1e-2,
        "lr_k": 8e-3,
        "lambda_x": 0.005,
        "lambda_k_l2": 8e-4,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.01,
        "kernel_size": 19,
        "sigma_gaussian": 2.0,
        "angle_motion": 35.0,
    },
    {
        "name": "large_kernel_pink_diffusion",
        "num_iters": 180,
        "lr_x": 9e-3,
        "lr_k": 7e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 5e-4,
        "lambda_k_center": 8e-4,
        "lambda_pink": 0.1,
        "lambda_diffusion": 0.02,
        "kernel_size": 27,
        "sigma_gaussian": 2.8,
        "angle_motion": 60.0,
    },
    {
        "name": "gaussian_heavy_blur",
        "num_iters": 140,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 23,
        "sigma_gaussian": 4.0,
        "angle_motion": 0.0,
    },
    {
        "name": "motion_sharp_angle",
        "num_iters": 130,
        "lr_x": 1e-2,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 7e-4,
        "lambda_k_center": 7e-4,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.01,
        "kernel_size": 21,
        "sigma_gaussian": 2.0,
        "angle_motion": 85.0,
    },
    {
        "name": "diagonal_motion_low_lr",
        "num_iters": 160,
        "lr_x": 6e-3,
        "lr_k": 6e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.015,
        "kernel_size": 17,
        "sigma_gaussian": 2.0,
        "angle_motion": 45.0,
    },
    {
        "name": "long_run_low_lr",
        "num_iters": 250,
        "lr_x": 5e-3,
        "lr_k": 5e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 15,
        "sigma_gaussian": 1.8,
        "angle_motion": 0.0,
    },
    {
        "name": "long_run_with_priors",
        "num_iters": 250,
        "lr_x": 6e-3,
        "lr_k": 6e-3,
        "lambda_x": 0.01,
        "lambda_k_l2": 8e-4,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.01,
        "kernel_size": 21,
        "sigma_gaussian": 2.5,
        "angle_motion": 30.0,
    },
    {
        "name": "high_iters_small_step",
        "num_iters": 300,
        "lr_x": 3e-3,
        "lr_k": 3e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 17,
        "sigma_gaussian": 1.5,
        "angle_motion": 10.0,
    },
    {
        "name": "diffusion_strong",
        "num_iters": 120,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 5e-4,
        "lambda_k_center": 5e-4,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.05,
        "kernel_size": 15,
        "sigma_gaussian": 1.8,
        "angle_motion": 0.0,
    },
    {
        "name": "pink_strong_center",
        "num_iters": 140,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 7e-4,
        "lambda_k_center": 2e-3,
        "lambda_pink": 0.2,
        "lambda_diffusion": 0.0,
        "kernel_size": 19,
        "sigma_gaussian": 2.2,
        "angle_motion": 20.0,
    },
    {
        "name": "pink_diffusion_mid",
        "num_iters": 150,
        "lr_x": 1e-2,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.1,
        "lambda_diffusion": 0.02,
        "kernel_size": 17,
        "sigma_gaussian": 2.0,
        "angle_motion": 40.0,
    },
    {
        "name": "weak_l2_regularization",
        "num_iters": 110,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-4,
        "lambda_k_center": 5e-4,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.005,
        "kernel_size": 13,
        "sigma_gaussian": 1.6,
        "angle_motion": 5.0,
    },
    {
        "name": "strong_l2_regularization",
        "num_iters": 110,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 5e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 15,
        "sigma_gaussian": 2.0,
        "angle_motion": 0.0,
    },
    {
        "name": "low_iters_warmup",
        "num_iters": 40,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.01,
        "kernel_size": 11,
        "sigma_gaussian": 1.4,
        "angle_motion": 0.0,
    },
    {
        "name": "high_iters_motion",
        "num_iters": 220,
        "lr_x": 7e-3,
        "lr_k": 7e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.015,
        "kernel_size": 21,
        "sigma_gaussian": 2.2,
        "angle_motion": 70.0,
    },
    {
        "name": "balanced_all_priors",
        "num_iters": 160,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.01,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.01,
        "kernel_size": 19,
        "sigma_gaussian": 2.0,
        "angle_motion": 30.0,
    },
    {
        "name": "pink_only_large_kernel",
        "num_iters": 130,
        "lr_x": 9e-3,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 8e-4,
        "lambda_k_center": 8e-4,
        "lambda_pink": 0.2,
        "lambda_diffusion": 0.0,
        "kernel_size": 27,
        "sigma_gaussian": 2.5,
        "angle_motion": 55.0,
    },
    {
        "name": "diffusion_only_large_kernel",
        "num_iters": 130,
        "lr_x": 9e-3,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 8e-4,
        "lambda_k_center": 8e-4,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.03,
        "kernel_size": 27,
        "sigma_gaussian": 2.5,
        "angle_motion": 55.0,
    },
    {
        "name": "image_prior_only",
        "num_iters": 100,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.03,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 15,
        "sigma_gaussian": 1.8,
        "angle_motion": 10.0,
    },
    {
        "name": "image_prior_plus_center",
        "num_iters": 120,
        "lr_x": 1e-2,
        "lr_k": 9e-3,
        "lambda_x": 0.02,
        "lambda_k_l2": 8e-4,
        "lambda_k_center": 2e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.005,
        "kernel_size": 17,
        "sigma_gaussian": 1.9,
        "angle_motion": 20.0,
    },
    {
        "name": "pink_diffusion_center",
        "num_iters": 140,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 2e-3,
        "lambda_pink": 0.1,
        "lambda_diffusion": 0.02,
        "kernel_size": 19,
        "sigma_gaussian": 2.0,
        "angle_motion": 35.0,
    },
    {
        "name": "gaussian_small_sigma",
        "num_iters": 90,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 13,
        "sigma_gaussian": 0.8,
        "angle_motion": 0.0,
    },
    {
        "name": "gaussian_large_sigma",
        "num_iters": 90,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.0,
        "kernel_size": 17,
        "sigma_gaussian": 4.5,
        "angle_motion": 0.0,
    },
    {
        "name": "motion_small_angle",
        "num_iters": 110,
        "lr_x": 1e-2,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.01,
        "kernel_size": 15,
        "sigma_gaussian": 1.8,
        "angle_motion": 5.0,
    },
    {
        "name": "motion_large_angle",
        "num_iters": 110,
        "lr_x": 1e-2,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.01,
        "kernel_size": 15,
        "sigma_gaussian": 1.8,
        "angle_motion": 170.0,
    },
    {
        "name": "asymmetric_lr",
        "num_iters": 130,
        "lr_x": 1.5e-2,
        "lr_k": 5e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.01,
        "kernel_size": 19,
        "sigma_gaussian": 2.0,
        "angle_motion": 60.0,
    },
    {
        "name": "kernel_center_heavy",
        "num_iters": 140,
        "lr_x": 1e-2,
        "lr_k": 1e-2,
        "lambda_x": 0.0,
        "lambda_k_l2": 8e-4,
        "lambda_k_center": 3e-3,
        "lambda_pink": 0.0,
        "lambda_diffusion": 0.005,
        "kernel_size": 17,
        "sigma_gaussian": 1.8,
        "angle_motion": 25.0,
    },
    {
        "name": "low_diffusion_high_pink",
        "num_iters": 150,
        "lr_x": 1e-2,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.2,
        "lambda_diffusion": 0.005,
        "kernel_size": 15,
        "sigma_gaussian": 2.0,
        "angle_motion": 50.0,
    },
    {
        "name": "low_pink_high_diffusion",
        "num_iters": 150,
        "lr_x": 1e-2,
        "lr_k": 9e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 1e-3,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.05,
        "lambda_diffusion": 0.04,
        "kernel_size": 15,
        "sigma_gaussian": 2.0,
        "angle_motion": 50.0,
    },
    {
        "name": "long_kernel_experiment",
        "num_iters": 180,
        "lr_x": 8e-3,
        "lr_k": 8e-3,
        "lambda_x": 0.0,
        "lambda_k_l2": 7e-4,
        "lambda_k_center": 1e-3,
        "lambda_pink": 0.1,
        "lambda_diffusion": 0.02,
        "kernel_size": 33,
        "sigma_gaussian": 3.2,
        "angle_motion": 90.0,
    },
]
